In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/district_population_timeseries.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/district_population_timeseries.csv'

In [2]:
import os
os.getcwd()

'/Users/denzelngabo/Desktop/UrbanPlus_API/notebooks/notebooks'

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/district_population_timeseries.csv")
df.head()

   year district  population
0  2000   Gasabo      316528
1  2000  Musanze      301451
2  2001   Gasabo      328887
3  2001  Musanze      306421
4  2002   Gasabo      343031

In [3]:
train = df[df ["year"] <= 2015]
test = df[df ["year"] > 2015]

print("Train rows:", len(train))
print("Test rows:", len(test))

Train rows: 32
Test rows: 10

In [7]:
from sklearn.linear_model import LinearRegression


gasabo_train = train[train["district"] == "Gasabo"]
gasabo_test = test[test["district"] == "Gasabo"]

X_train = gasabo_train[["year"]]
y_train = gasabo_train["population"]

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(gasabo_test[["year"]])

results = gasabo_test[["year", "population"]].copy()
results["predicted_population"] = predictions.round()
results["error_%"] = (((results["predicted_population"] - results["population"]) / results["population"]) * 100).round(1)
results

    year  population  predicted_population  error_%
32  2016      694635              647942.0     -6.7
34  2017      736235              670267.0     -9.0
36  2018      781024              692592.0    -11.3
38  2019      830744              714916.0    -13.9
40  2020      883424              737241.0    -16.5

In [8]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

results["rf_predicted"] = rf.predict(gasabo_test[["year"]]).round()
results["rf_error_%"] = ((results["rf_predicted"] - results["population"]) / results["population"] * 100).round(1)
results

    year  population  predicted_population  error_%  rf_predicted  rf_error_%
32  2016      694635              647942.0     -6.7      635850.0        -8.5
34  2017      736235              670267.0     -9.0      635850.0       -13.6
36  2018      781024              692592.0    -11.3      635850.0       -18.6
38  2019      830744              714916.0    -13.9      635850.0       -23.5
40  2020      883424              737241.0    -16.5      635850.0       -28.0

In [10]:
import numpy as np 

log_model = LinearRegression()
log_model.fit(X_train, np.log(y_train))

log_predictions = log_model.predict(gasabo_test[["year"]])
results["log_predicted"] = np.exp(log_predictions).round()
results["log_error_%"] = ((results["log_predicted"] - results["population"]) / results["population"] * 100).round(1)
results

,year,population,predicted_population,error_%,rf_predicted,rf_error_%,log_predicted,log_error_%
32,2016,694635,647942.0,-6.7,635850.0,-8.5,676148.0,-2.7
34,2017,736235,670267.0,-9.0,635850.0,-13.6,709944.0,-3.6
36,2018,781024,692592.0,-11.3,635850.0,-18.6,745430.0,-4.6
38,2019,830744,714916.0,-13.9,635850.0,-23.5,782689.0,-5.8
40,2020,883424,737241.0,-16.5,635850.0,-28.0,821810.0,-7.0